[package]
name = "zombrise_client"
version = "0.1.0"
edition = "2021"

[dependencies]
zombrise_shared = { path = "../shared", features = ["client"] }
bevy = { version = "0.16", default-features = false, features = [
    "bevy_asset",
    "bevy_scene",
    "bevy_gltf",
    "serialize",
    "animation",
    "bevy_ui",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_render",
    "bevy_text",
    "bevy_sprite",
    "png",
    "jpeg",
    "tonemapping_luts",
    "default_font",
    "x11",
    "wayland",
    "bevy_state",
] }
bevy_replicon = "0.33"
bevy_replicon_renet2 = "0.9"
renet2_netcode = "0.9"
bevy_simple_text_input = "0.11"
arboard = "3.6"
