[package]
name = "dragon_queen_shared"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", default-features = false, features = ["bevy_asset", "bevy_scene", "bevy_gltf", "serialize", "animation", "bevy_state", "bevy_pbr", "bevy_render", "bevy_core_pipeline"] }
bevy_input = "0.14"
bevy_replicon = "0.27"
bevy_replicon_renet = "0.4"
bevy_rapier3d = "0.27"
serde = { version = "1.0", features = ["derive"] }
rand = "0.9.2"
